import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared-pages/Navbar";
import Footer from "@/components/shared-pages/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className}  h-full antialiased`}>
      <body
        suppressHydrationWarning={true}
        className="min-h-full flex flex-col"
      >
        <Navbar></Navbar>
        <main>{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
